version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    restart: always
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=laravel
      - MARIADB_DATABASE=laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1   
    ports:
      - "8080:80"
    depends_on:
      - mariadb

  myapp:
    image: docker.io/bitnami/laravel:10
    restart: always
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=laravel
      - DB_DATABASE=laravel
    volumes:
      - './src:/app'
    depends_on:
      - mariadb
