version: '2'

services:
  mariadb:
    image: mariadb:10.4
    command:
      --max_allowed_packet=64M
      --optimizer_use_condition_selectivity=1
      --optimizer_switch="rowid_filter=off"
    ports:
      - "3306:3306"
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file: env/db.env
    ports:
      - "8080:80"
    depends_on:
      - mariadb

  app:
    image: docker.io/bitnami/laravel:10
    restart: always
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=laravel
      - DB_DATABASE=laravel
    volumes:
      - './src:/app'
      - ~/.composer:/var/www/.composer:cached
    depends_on:
      - mariadb
      
volumes:
    dbdata: